/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Copy: typeof import('./src/components/copy/index.vue')['default']
    IconFont: typeof import('./src/components/IconFont/index.vue')['default']
    InnerLink: typeof import('./src/components/InnerLink/index.vue')['default']
    Loading: typeof import('./src/components/SunLoading/Loading.vue')['default']
    NumberWithUnit: typeof import('./src/components/NumberWithUnit/index.vue')['default']
    PledgeMining: typeof import('./src/components/Application/src/PledgeMining.vue')['default']
    ReChangeModal: typeof import('./src/components/ReChangeModal/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareCodeShow: typeof import('./src/components/Application/src/shareCodeShow.vue')['default']
    SunDrawer: typeof import('./src/components/SunDrawer/index.vue')['default']
    SunHeaderNav: typeof import('./src/components/SunHeaderNav/index.vue')['default']
    SunModal: typeof import('./src/components/SunModal/index.vue')['default']
    SunPage: typeof import('./src/components/SunPage/index.vue')['default']
    SunPicker: typeof import('./src/components/SunPicker/index.vue')['default']
    SunRechange: typeof import('./src/components/Application/src/SunRechange.vue')['default']
    SunSelect: typeof import('./src/components/SunSelect/index.vue')['default']
    SunTabBar: typeof import('./src/components/SunTabBar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TopFixed: typeof import('./src/components/TopFixed/index.vue')['default']
  }
}
