<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *php artisan db:seed --class=MenusTableSeeder
     * @return void
     */
    public function run()
    {
        $menus = array(
            array('id' => '1', 'name' => 'workplace', 'title' => '工作台', 'icon' => 'DashboardOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/workplace', 'component' => '@/pages/workplace', 'renderMenu' => '1', 'parent' => NULL, 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => NULL, 'updated_at' => '2024-08-06 15:01:10'),
            array('id' => '6', 'name' => 'system', 'title' => '系统配置', 'icon' => 'SettingOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/system', 'component' => '@/components/layout/BlankView.vue', 'renderMenu' => '1', 'parent' => NULL, 'permission' => NULL, 'cacheable' => '1', 'sort' => '99', 'link' => NULL, 'created_at' => NULL, 'updated_at' => '2024-08-07 08:56:44'),
            array('id' => '8', 'name' => 'menu', 'title' => '菜单管理', 'icon' => NULL, 'badge' => '', 'target' => '_self', 'path' => '/system/menu', 'component' => '@/pages/system', 'renderMenu' => '1', 'parent' => 'system', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '12', 'name' => 'roles', 'title' => '角色管理', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/system/roles', 'component' => '@/pages/roles', 'renderMenu' => '1', 'parent' => 'system', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '13', 'name' => 'lang', 'title' => '多语言配置', 'icon' => 'TranslationOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/lang', 'component' => '@/components/layout/BlankView.vue', 'renderMenu' => '1', 'parent' => NULL, 'permission' => NULL, 'cacheable' => '1', 'sort' => '11', 'link' => NULL, 'created_at' => '2024-07-03 13:38:36', 'updated_at' => '2024-08-07 08:58:26'),
            array('id' => '14', 'name' => 'lang_list', 'title' => '语言列表', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/lang/lang_list', 'component' => '@/pages/lang/list/index.vue', 'renderMenu' => '1', 'parent' => 'lang', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-03 13:39:51', 'updated_at' => '2024-07-03 13:40:52'),
            array('id' => '15', 'name' => 'lang_i18n', 'title' => '语言配置', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/lang/lang_i18n', 'component' => '@/pages/lang/i18n/index.vue', 'renderMenu' => '1', 'parent' => 'lang', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-03 13:42:16', 'updated_at' => '2024-07-03 13:42:16'),
            array('id' => '16', 'name' => 'membership_levels', 'title' => '会员等级', 'icon' => 'ApartmentOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/people/membership_levels', 'component' => '@/pages/people/membership_levels', 'renderMenu' => '1', 'parent' => 'people', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-09 15:25:57', 'updated_at' => '2024-07-22 10:46:31'),
            array('id' => '18', 'name' => 'pool', 'title' => '矿池管理', 'icon' => 'AreaChartOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/pool', 'component' => '@/components/layout/BlankView.vue', 'renderMenu' => '1', 'parent' => NULL, 'permission' => NULL, 'cacheable' => '1', 'sort' => '2', 'link' => NULL, 'created_at' => '2024-07-11 17:04:59', 'updated_at' => '2024-08-07 08:57:05'),
            array('id' => '19', 'name' => 'poolList', 'title' => '矿池列表', 'icon' => 'AimOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/pool/poolList', 'component' => '@/pages/pool/poolList', 'renderMenu' => '1', 'parent' => 'pool', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-11 17:08:02', 'updated_at' => '2024-07-11 17:14:59'),
            array('id' => '20', 'name' => 'pledgeOrder', 'title' => '质押订单列表', 'icon' => 'AccountBookOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/pool/pledgeOrder', 'component' => '@/pages/pool/pledgeOrder', 'renderMenu' => '1', 'parent' => 'pool', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-11 17:25:48', 'updated_at' => '2024-07-12 09:16:35'),
            array('id' => '21', 'name' => 'pledgeIncome', 'title' => '质押收益记录', 'icon' => 'AlipayCircleOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/pool/pledgeIncome', 'component' => '@/pages/pool/pledgeIncome', 'renderMenu' => '1', 'parent' => 'pool', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-11 17:32:19', 'updated_at' => '2024-07-12 09:16:22'),
            array('id' => '22', 'name' => 'pledgePeriod', 'title' => '质押周期列表', 'icon' => 'BorderlessTableOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/pool/pledgePeriod', 'component' => '@/pages/pool/pledgePeriod', 'renderMenu' => '1', 'parent' => 'pool', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-11 17:34:12', 'updated_at' => '2024-07-11 17:34:12'),
            array('id' => '23', 'name' => 'currency', 'title' => '币种管理', 'icon' => 'BoldOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/currency', 'component' => '@/pages/currency', 'renderMenu' => '1', 'parent' => NULL, 'permission' => NULL, 'cacheable' => '1', 'sort' => '3', 'link' => NULL, 'created_at' => '2024-07-11 17:36:49', 'updated_at' => '2024-08-07 08:57:17'),
            array('id' => '24', 'name' => 'config', 'title' => '配置管理', 'icon' => '', 'badge' => NULL, 'target' => '_self', 'path' => '/system/config', 'component' => '@/pages/system/config', 'renderMenu' => '1', 'parent' => 'system', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-20 10:32:26', 'updated_at' => '2024-08-07 09:08:30'),
            array('id' => '25', 'name' => 'user', 'title' => '用户列表', 'icon' => 'AliwangwangOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/people/user', 'component' => '@/pages/people/user', 'renderMenu' => '1', 'parent' => 'people', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-22 09:15:14', 'updated_at' => '2024-07-22 10:46:22'),
            array('id' => '26', 'name' => 'people', 'title' => '用户管理', 'icon' => 'AndroidOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/people', 'component' => '@/components/layout/BlankView.vue', 'renderMenu' => '1', 'parent' => NULL, 'permission' => NULL, 'cacheable' => '1', 'sort' => '1', 'link' => NULL, 'created_at' => '2024-07-22 10:46:03', 'updated_at' => '2024-08-07 08:56:55'),
            array('id' => '27', 'name' => 'withdrawalManage', 'title' => '提现管理', 'icon' => 'AccountBookOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/Withdrawals/withdrawalManage', 'component' => '@/pages/Withdrawals/withdrawalManage', 'renderMenu' => '1', 'parent' => 'Withdrawals', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-22 10:55:14', 'updated_at' => '2024-08-06 14:11:10'),
            array('id' => '28', 'name' => 'Withdrawals', 'title' => '审核中心', 'icon' => 'AlibabaOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/Withdrawals', 'component' => '@/components/layout/BlankView.vue', 'renderMenu' => '1', 'parent' => NULL, 'permission' => NULL, 'cacheable' => '1', 'sort' => '4', 'link' => NULL, 'created_at' => '2024-07-22 14:45:50', 'updated_at' => '2024-08-07 08:58:03'),
            array('id' => '29', 'name' => 'WithdrawalRecord', 'title' => '提现记录', 'icon' => 'AppstoreAddOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/Withdrawals/WithdrawalRecord', 'component' => '@/pages/Withdrawals/WithdrawalRecord', 'renderMenu' => '0', 'parent' => 'Withdrawals', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-23 10:23:48', 'updated_at' => '2024-08-13 10:21:50'),
            array('id' => '30', 'name' => 'proxy', 'title' => '代理查询', 'icon' => 'CloudServerOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/people/proxy', 'component' => '@/pages/people/proxy', 'renderMenu' => '0', 'parent' => 'people', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-23 14:39:00', 'updated_at' => '2024-07-23 16:40:50'),
            array('id' => '31', 'name' => 'financialCenter', 'title' => '财务中心', 'icon' => 'AccountBookOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/financialCenter', 'component' => '@/components/layout/BlankView.vue', 'renderMenu' => '1', 'parent' => NULL, 'permission' => NULL, 'cacheable' => '1', 'sort' => '5', 'link' => NULL, 'created_at' => '2024-07-24 11:09:43', 'updated_at' => '2024-08-07 08:58:14'),
            array('id' => '32', 'name' => 'detailed', 'title' => '资产变动明细', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/financialCenter/detailed', 'component' => '@/pages/financialCenter/detailed', 'renderMenu' => '1', 'parent' => 'financialCenter', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-24 11:10:48', 'updated_at' => '2024-07-24 11:10:48'),
            array('id' => '33', 'name' => 'recharge', 'title' => '充值记录', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/financialCenter/recharge', 'component' => '@/pages/financialCenter/recharge', 'renderMenu' => '1', 'parent' => 'financialCenter', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-24 11:11:31', 'updated_at' => '2024-08-13 10:47:04'),
            array('id' => '34', 'name' => 'Withdrawal', 'title' => '提现记录', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/financialCenter/Withdrawal', 'component' => '@/pages/financialCenter/Withdrawal', 'renderMenu' => '1', 'parent' => 'financialCenter', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-24 11:12:41', 'updated_at' => '2024-07-24 11:12:41'),
            array('id' => '35', 'name' => 'wevConfig', 'title' => '网站配置', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/system/wevConfig', 'component' => '@/pages/system/wevConfig', 'renderMenu' => '1', 'parent' => 'system', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-07-25 17:01:50', 'updated_at' => '2024-07-25 17:02:13'),
            array('id' => '36', 'name' => 'account', 'title' => '账号管理', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/system/account', 'component' => '@/pages/account', 'renderMenu' => '1', 'parent' => 'system', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-08-06 16:54:38', 'updated_at' => '2024-08-07 09:04:53'),
            array('id' => '37', 'name' => 'loan', 'title' => '借款管理', 'icon' => 'DollarCircleOutlined', 'badge' => NULL, 'target' => '_self', 'path' => '/loan', 'component' => '@/components/layout/BlankView.vue', 'renderMenu' => '1', 'parent' => NULL, 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-11-14 10:29:08', 'updated_at' => '2024-11-14 10:29:08'),
            array('id' => '38', 'name' => 'loanList', 'title' => '借款管理', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/loan/loanList', 'component' => '@/pages/loan/loanList', 'renderMenu' => '1', 'parent' => 'loan', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-11-14 10:36:45', 'updated_at' => '2024-11-14 10:36:56'),
            array('id' => '39', 'name' => 'notice', 'title' => '公告配置', 'icon' => NULL, 'badge' => NULL, 'target' => '_self', 'path' => '/system/notice', 'component' => '@/pages/system/notice/Notice.vue', 'renderMenu' => '1', 'parent' => 'system', 'permission' => NULL, 'cacheable' => '1', 'sort' => '0', 'link' => NULL, 'created_at' => '2024-11-28 03:58:37', 'updated_at' => '2024-11-28 03:58:37')
        );

        DB::table('menus')->insert($menus);
    }
}
